name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: ${{github.workspace}}/spack       # Where to clone Spack

    - name: Install TFEL and Enzyme
      shell: spack-sh {0}
      run: |
	wget https://apt.llvm.org/llvm.sh
	chmod +x llvm.sh
	sudo ./llvm.sh 18
        spack external find llvm
	spack compiler find
        sed -i 's|prefix: /usr|prefix: /usr/lib/llvm-18/|g' /home/runner/work/TFELMathEnzyme/TFELMathEnzyme/spack/etc/spack/packages.yaml
        spack install enzyme%clang@18.1.8
        spack install tfel@master~python~python_bindings~aster~fortran~abaqus~calculix~ansys~europlexus~cyrano~lsdyna~comsol~diana-fea%clang@18.1.8
    - name: cmake
      shell: spack-sh {0}
      run: |
        spack load tfel enzyme
        cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      shell: spack-sh {0}
      run: |
        spack load tfel enzyme
        make
    - name: ctest
      shell: spack-sh {0}
      run: |
        spack load tfel enzyme
        ctest
